/**
 * GENERATED by scripts/sync-capture-manifest.mjs from public/captures/manifest.json. Do not edit.
 * Real MockLoft screenshots recorded by tools/play-maya.ts, used by fixture mode as painting textures.
 */
import type { App } from "@cortex/schema";

export interface CaptureManifestEntry {
  file: string;
  app: App;
  action: "load" | "click" | "submit" | "dwell";
  episode: string;
  day: number;
  title: string;
  listingId: string | null;
}

export const CAPTURE_MANIFEST: readonly CaptureManifestEntry[] = [
  {
    "file": "/captures/001-mockloft-load.webp",
    "app": "mockloft",
    "action": "load",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Listings",
    "listingId": null
  },
  {
    "file": "/captures/002-mockloft-dwell.webp",
    "app": "mockloft",
    "action": "dwell",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Listings",
    "listingId": null
  },
  {
    "file": "/captures/003-mockloft-load.webp",
    "app": "mockloft",
    "action": "load",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Renovated 1BR in Greenpoint",
    "listingId": "listing:110"
  },
  {
    "file": "/captures/004-mockloft-dwell.webp",
    "app": "mockloft",
    "action": "dwell",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Renovated 1BR in Greenpoint",
    "listingId": "listing:110"
  },
  {
    "file": "/captures/005-mockloft-click.webp",
    "app": "mockloft",
    "action": "click",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Renovated 1BR in Greenpoint",
    "listingId": "listing:110"
  },
  {
    "file": "/captures/006-mockloft-load.webp",
    "app": "mockloft",
    "action": "load",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Loft-style 2BR in East Williamsburg",
    "listingId": "listing:102"
  },
  {
    "file": "/captures/007-mockloft-dwell.webp",
    "app": "mockloft",
    "action": "dwell",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Loft-style 2BR in East Williamsburg",
    "listingId": "listing:102"
  },
  {
    "file": "/captures/008-mockloft-click.webp",
    "app": "mockloft",
    "action": "click",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Loft-style 2BR in East Williamsburg",
    "listingId": "listing:102"
  },
  {
    "file": "/captures/009-mockloft-load.webp",
    "app": "mockloft",
    "action": "load",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Bright 2BR in Bushwick",
    "listingId": "listing:103"
  },
  {
    "file": "/captures/010-mockloft-dwell.webp",
    "app": "mockloft",
    "action": "dwell",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Bright 2BR in Bushwick",
    "listingId": "listing:103"
  },
  {
    "file": "/captures/011-landlord_chat-submit.webp",
    "app": "landlord_chat",
    "action": "submit",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Bright 2BR in Bushwick",
    "listingId": "listing:103"
  },
  {
    "file": "/captures/012-mockloft-load.webp",
    "app": "mockloft",
    "action": "load",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Sunny 1BR in Ridgewood",
    "listingId": "listing:112"
  },
  {
    "file": "/captures/013-mockloft-dwell.webp",
    "app": "mockloft",
    "action": "dwell",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Sunny 1BR in Ridgewood",
    "listingId": "listing:112"
  },
  {
    "file": "/captures/014-landlord_chat-submit.webp",
    "app": "landlord_chat",
    "action": "submit",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Sunny 1BR in Ridgewood",
    "listingId": "listing:112"
  },
  {
    "file": "/captures/015-mockloft-load.webp",
    "app": "mockloft",
    "action": "load",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Loft-style 2BR in East Williamsburg",
    "listingId": "listing:101"
  },
  {
    "file": "/captures/016-mockloft-dwell.webp",
    "app": "mockloft",
    "action": "dwell",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Loft-style 2BR in East Williamsburg",
    "listingId": "listing:101"
  },
  {
    "file": "/captures/017-landlord_chat-submit.webp",
    "app": "landlord_chat",
    "action": "submit",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Loft-style 2BR in East Williamsburg",
    "listingId": "listing:101"
  },
  {
    "file": "/captures/018-mockloft-load.webp",
    "app": "mockloft",
    "action": "load",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Loft-style 1BR in Williamsburg",
    "listingId": "listing:105"
  },
  {
    "file": "/captures/019-mockloft-dwell.webp",
    "app": "mockloft",
    "action": "dwell",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Loft-style 1BR in Williamsburg",
    "listingId": "listing:105"
  },
  {
    "file": "/captures/020-landlord_chat-submit.webp",
    "app": "landlord_chat",
    "action": "submit",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Loft-style 1BR in Williamsburg",
    "listingId": "listing:105"
  },
  {
    "file": "/captures/021-mockloft-load.webp",
    "app": "mockloft",
    "action": "load",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Loft-style 1BR in Bushwick",
    "listingId": "listing:111"
  },
  {
    "file": "/captures/022-mockloft-dwell.webp",
    "app": "mockloft",
    "action": "dwell",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Loft-style 1BR in Bushwick",
    "listingId": "listing:111"
  },
  {
    "file": "/captures/023-mockloft-click.webp",
    "app": "mockloft",
    "action": "click",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Loft-style 1BR in Bushwick",
    "listingId": "listing:111"
  },
  {
    "file": "/captures/024-mockloft-load.webp",
    "app": "mockloft",
    "action": "load",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Bright 2BR in Bushwick",
    "listingId": "listing:104"
  },
  {
    "file": "/captures/025-mockloft-dwell.webp",
    "app": "mockloft",
    "action": "dwell",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Bright 2BR in Bushwick",
    "listingId": "listing:104"
  },
  {
    "file": "/captures/026-mockloft-click.webp",
    "app": "mockloft",
    "action": "click",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Bright 2BR in Bushwick",
    "listingId": "listing:104"
  },
  {
    "file": "/captures/027-mockloft-load.webp",
    "app": "mockloft",
    "action": "load",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Loft-style 1BR in Williamsburg",
    "listingId": "listing:106"
  },
  {
    "file": "/captures/028-mockloft-dwell.webp",
    "app": "mockloft",
    "action": "dwell",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Loft-style 1BR in Williamsburg",
    "listingId": "listing:106"
  },
  {
    "file": "/captures/029-mockloft-click.webp",
    "app": "mockloft",
    "action": "click",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Loft-style 1BR in Williamsburg",
    "listingId": "listing:106"
  },
  {
    "file": "/captures/030-mockloft-load.webp",
    "app": "mockloft",
    "action": "load",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Garden-level Studio in Williamsburg",
    "listingId": "listing:107"
  },
  {
    "file": "/captures/031-mockloft-dwell.webp",
    "app": "mockloft",
    "action": "dwell",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Garden-level Studio in Williamsburg",
    "listingId": "listing:107"
  },
  {
    "file": "/captures/032-landlord_chat-submit.webp",
    "app": "landlord_chat",
    "action": "submit",
    "episode": "hunt1-day2",
    "day": 2,
    "title": "MockLoft · Garden-level Studio in Williamsburg",
    "listingId": "listing:107"
  },
  {
    "file": "/captures/033-inbox-load.webp",
    "app": "inbox",
    "action": "load",
    "episode": "life-day2",
    "day": 2,
    "title": "Inbox",
    "listingId": null
  },
  {
    "file": "/captures/034-inbox-click.webp",
    "app": "inbox",
    "action": "click",
    "episode": "life-day2",
    "day": 2,
    "title": "Inbox",
    "listingId": null
  },
  {
    "file": "/captures/035-inbox-load.webp",
    "app": "inbox",
    "action": "load",
    "episode": "life-day2",
    "day": 2,
    "title": "Inbox · newsletter",
    "listingId": null
  }
];
